### ISSUE TITLE
Calling the translate() function results in "Requests to this API [...] are blocked" error

### ISSUE THREAD

**Issue by mathiasm74** [franciscop/translate#29] opened 2021-07-28 16:10 UTC
As per the title. The full error is "Error: Requests to this API translate method google.cloud.translate.v2.TranslateService.TranslateText are blocked." 

Is this because the v2 API has been deprecated (current version is v3)? Not been able to find any info about this.

**Comment by franciscop** [comment] 2021-07-28 21:30
Unfortunately I have been unable to test with Google Translate since they moved to corporate and required a Google Cloud account to test it out (I'm def not going to sign up to Google Cloud, specially only to maintain this project).

If you find a solution please feel free to share or send a PR. I know it used to work with Google Translate when it was released, unknown as of now.

**Comment by franciscop** [comment] 2021-09-07 21:20
Duplicate of https://github.com/franciscop/translate/issues/27

**Closed by franciscop** 2021-09-07 21:20 UTC
